title: "[Q&A] "
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (Optional)
      description: Error messages, what you tried, etc.
    validations:
      required: false
